### ISSUE TITLE
[DOC] Update incorrect URL on README.md

### ISSUE THREAD

**Issue by ingo** [Axway/amplify-central#65]
## Issue description

I'm filing this as an issue because I'm not positive of the fix, but I believe the link to https://axway-open-docs.netlify.app/ in README.md should point to https://amplify-central.netlify.app/ instead (there are two links in that document).

## Problem location

README.md

## Suggestions for a fix

Update the URL

**Comment by lbadenhop** [comment]
@ingo The Readme has been corrected with https://github.com/Axway/amplify-central/pull/83.
